<script lang="ts">
	import { Panel } from '$lib/components/common';
	import { allNewsItems, indices, crypto, digest, dgxEnabled } from '$lib/stores';
	import { analyzeCorrelations } from '$lib/analysis/correlation';

	// Build the payload from current store state and trigger generation
	async function generate() {
		const news = $allNewsItems;
		const correlationResults = analyzeCorrelations(news);

		const headlines = news.slice(0, 80).map((n) => n.title);

		const correlations = correlationResults
			? [
					...correlationResults.emergingPatterns.map((p) => ({
						name: p.name,
						level: p.level,
						count: p.count,
						sourceCount: p.sources.length
					})),
					...correlationResults.crossSourceCorrelations.map((c) => ({
						name: c.name,
						level: c.level,
						sourceCount: c.sourceCount
					}))
				]
			: [];

		const markets = [
			...$indices.items.map((m) => ({
				symbol: m.symbol,
				name: m.name,
				changePercent: m.changePercent
			})),
			...$crypto.items.slice(0, 4).map((c) => ({
				symbol: c.symbol,
				name: c.name,
				changePercent: c.price_change_percentage_24h
			}))
		];

		await digest.generate({ headlines, correlations, markets });
	}

	// Auto-generate on first mount when DGX is enabled and we have news
	let autoGenerated = false;
	$effect(() => {
		if (!autoGenerated && $dgxEnabled && $allNewsItems.length > 0 && !$digest.data) {
			autoGenerated = true;
			generate();
		}
	});

	function formatTime(ts: number): string {
		return new Date(ts).toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' });
	}

	const significanceClass: Record<string, string> = {
		HIGH: 'sig-high',
		MEDIUM: 'sig-medium',
		LOW: 'sig-low'
	};

	const directionClass: Record<string, string> = {
		'RISK-ON': 'dir-on',
		'RISK-OFF': 'dir-off',
		MIXED: 'dir-mixed',
		FLAT: 'dir-flat'
	};
</script>

<Panel
	id="digest"
	title="Daily Digest"
	loading={$digest.loading}
	error={$digest.error}
	status={$digest.data ? `Generated ${formatTime($digest.data.generatedAt)}` : ''}
>
	{#snippet actions()}
		<button class="gen-btn" onclick={generate} disabled={$digest.loading}>
			{$digest.loading ? 'Generating…' : $digest.data ? 'Regenerate' : 'Generate Brief'}
		</button>
	{/snippet}

	{#if !$digest.data && !$digest.loading && !$digest.error}
		<div class="empty-state">
			{#if !$dgxEnabled}
				<p>Enable DGX LLM in settings to generate an AI-powered brief.</p>
			{:else}
				<p>Click <strong>Generate Brief</strong> to synthesize current headlines into a situation brief.</p>
			{/if}
		</div>
	{:else if $digest.data}
		{@const d = $digest.data}

		<!-- Top Signal -->
		<div class="section top-signal {significanceClass[d.topSignal.significance]}">
			<div class="sig-label">{d.topSignal.significance} SIGNAL</div>
			<div class="sig-headline">{d.topSignal.headline}</div>
			<div class="sig-detail">{d.topSignal.detail}</div>
		</div>

		<!-- Overnight -->
		{#if d.overnight.length > 0}
			<div class="section">
				<div class="section-title">Overnight</div>
				{#each d.overnight as item}
					<div class="overnight-row">
						<span class="overnight-cat">{item.category}</span>
						<span class="overnight-summary">{item.summary}</span>
					</div>
				{/each}
			</div>
		{/if}

		<!-- Market Context -->
		<div class="section market-ctx">
			<div class="section-title">Markets</div>
			<div class="direction-badge {directionClass[d.marketContext.direction]}">
				{d.marketContext.direction}
			</div>
			{#each d.marketContext.notes as note}
				<div class="market-note">{note}</div>
			{/each}
		</div>

		<!-- Watch Today -->
		{#if d.watchToday.length > 0}
			<div class="section">
				<div class="section-title">Watch Today</div>
				{#each d.watchToday as item}
					<div class="watch-item">
						<span class="watch-dot">›</span>
						{item}
					</div>
				{/each}
			</div>
		{/if}

		<!-- Noise Filter -->
		{#if d.noiseFilter.length > 0}
			<div class="section noise">
				<div class="section-title">Noise Filter</div>
				{#each d.noiseFilter as item}
					<div class="noise-item">{item}</div>
				{/each}
			</div>
		{/if}

		<div class="footer">via {d.model} · {formatTime(d.generatedAt)}</div>
	{/if}
</Panel>

<style>
	.empty-state {
		padding: 2rem 1rem;
		text-align: center;
		color: var(--text-muted);
		font-size: 0.85rem;
		line-height: 1.5;
	}

	.gen-btn {
		font-size: 0.75rem;
		padding: 0.2rem 0.6rem;
		border-radius: 4px;
		border: 1px solid var(--border);
		background: var(--bg-secondary);
		color: var(--text-primary);
		cursor: pointer;
		white-space: nowrap;
	}

	.gen-btn:hover:not(:disabled) {
		background: var(--accent);
		border-color: var(--accent);
		color: #fff;
	}

	.gen-btn:disabled {
		opacity: 0.5;
		cursor: not-allowed;
	}

	.section {
		padding: 0.75rem 1rem;
		border-bottom: 1px solid var(--border);
	}

	.section:last-of-type {
		border-bottom: none;
	}

	.section-title {
		font-size: 0.65rem;
		font-weight: 600;
		text-transform: uppercase;
		letter-spacing: 0.08em;
		color: var(--text-muted);
		margin-bottom: 0.5rem;
	}

	/* Top signal */
	.top-signal {
		border-left: 3px solid var(--border);
	}

	.top-signal.sig-high {
		border-left-color: var(--danger, #ef4444);
		background: color-mix(in srgb, var(--danger, #ef4444) 8%, transparent);
	}

	.top-signal.sig-medium {
		border-left-color: var(--warning, #f59e0b);
		background: color-mix(in srgb, var(--warning, #f59e0b) 8%, transparent);
	}

	.top-signal.sig-low {
		border-left-color: var(--success, #22c55e);
		background: color-mix(in srgb, var(--success, #22c55e) 8%, transparent);
	}

	.sig-label {
		font-size: 0.6rem;
		font-weight: 700;
		letter-spacing: 0.1em;
		color: var(--text-muted);
		margin-bottom: 0.3rem;
	}

	.sig-high .sig-label { color: var(--danger, #ef4444); }
	.sig-medium .sig-label { color: var(--warning, #f59e0b); }
	.sig-low .sig-label { color: var(--success, #22c55e); }

	.sig-headline {
		font-size: 0.95rem;
		font-weight: 600;
		color: var(--text-primary);
		line-height: 1.3;
		margin-bottom: 0.4rem;
	}

	.sig-detail {
		font-size: 0.8rem;
		color: var(--text-secondary);
		line-height: 1.5;
	}

	/* Overnight */
	.overnight-row {
		display: flex;
		gap: 0.6rem;
		font-size: 0.8rem;
		line-height: 1.4;
		margin-bottom: 0.35rem;
	}

	.overnight-row:last-child { margin-bottom: 0; }

	.overnight-cat {
		flex-shrink: 0;
		font-weight: 600;
		color: var(--accent);
		font-size: 0.75rem;
		min-width: 6rem;
	}

	.overnight-summary {
		color: var(--text-secondary);
	}

	/* Market context */
	.direction-badge {
		display: inline-block;
		font-size: 0.7rem;
		font-weight: 700;
		letter-spacing: 0.08em;
		padding: 0.15rem 0.5rem;
		border-radius: 3px;
		margin-bottom: 0.5rem;
	}

	.dir-on  { background: color-mix(in srgb, #22c55e 20%, transparent); color: #22c55e; }
	.dir-off { background: color-mix(in srgb, #ef4444 20%, transparent); color: #ef4444; }
	.dir-mixed { background: color-mix(in srgb, #f59e0b 20%, transparent); color: #f59e0b; }
	.dir-flat { background: color-mix(in srgb, var(--text-muted) 20%, transparent); color: var(--text-muted); }

	.market-note {
		font-size: 0.8rem;
		color: var(--text-secondary);
		line-height: 1.4;
		margin-bottom: 0.25rem;
	}

	/* Watch today */
	.watch-item {
		font-size: 0.8rem;
		color: var(--text-secondary);
		line-height: 1.4;
		margin-bottom: 0.3rem;
		display: flex;
		gap: 0.4rem;
	}

	.watch-dot {
		color: var(--accent);
		font-weight: 700;
		flex-shrink: 0;
	}

	/* Noise */
	.noise {
		background: color-mix(in srgb, var(--text-muted) 5%, transparent);
	}

	.noise-item {
		font-size: 0.75rem;
		color: var(--text-muted);
		line-height: 1.4;
		margin-bottom: 0.25rem;
		text-decoration: line-through;
		text-decoration-color: color-mix(in srgb, var(--text-muted) 50%, transparent);
	}

	.noise-item:last-child { margin-bottom: 0; }

	/* Footer */
	.footer {
		padding: 0.4rem 1rem;
		font-size: 0.65rem;
		color: var(--text-muted);
		text-align: right;
		border-top: 1px solid var(--border);
	}
</style>
